name: Generate documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r software/requirements.txt
    - name: Build docs
      run: |
        python software/main.py
    - name: Archive documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: generated-docs
        path: doc
    - name: Move docs to Github Pages
      uses: actions/deploy-pages@v2.0.1
      with:
        artifact_name: generated-docs
